# Generated by Django 2.1.4 on 2019-02-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190217_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='weight_unit',
        ),
    ]
