# Generated by Django 2.1.4 on 2019-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190217_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
