# Generated by Django 2.1.4 on 2019-02-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190217_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
